// Nitin Joshi's archive, sorted into brand categories.
//
// Built on 2026-08-25 from the three exports in `nitin josi data/`:
//   ji_nitinjoshi_instagram.json   677 reels from the host's own account
//   nitinjoshi_notes.json          679 podcast clips from @nitinjoshi_notes
//   jinitinjoshi_youtube.json      31 full episodes
//
// Purpose: when the deck pitches a brand, slide 6 should show work from that
// brand's own category rather than whatever the keyword matcher surfaced. A
// jewellery brand sees the Rubans founder episode; a skincare brand sees
// Fixderma and the sunscreen test.
//
// Ranking inside a category, highest first:
//   1. `collab` — a real paid partnership with a brand in that vertical. The
//      strongest proof available, because it already happened.
//   2. `episode` — a full podcast episode with a founder from that vertical.
//   3. `clip` — the short-form cut of one of those episodes, from the
//      podcast's own account. Long-form plus clips is the package itself.
//   4. `case-study` — a high-engagement reel about that vertical.
//
// Engagement figures are as scraped on the export date and will drift; they
// are here to rank, not to print as current facts.

export const CONTENT_CATEGORIES = [
  {
    id: "direct-to-consumer",
    name: "Direct-to-Consumer",
    picks: [
      {
        brand: "Lenskart",
        type: "collab",
        platform: "instagram",
        title: "Got old specs? Don’t ditch them—upgrade them for FREE! 🔥 Just a ₹199 fitting charge, and Lenskart will swap out your len",
        url: "https://www.instagram.com/p/DHdfi51zOz_/",
        date: "2025-03-21",
        likes: 203297, comments: 3606,
        note: "Paid collaboration — free lens upgrade campaign, the account's best-performing brand post.",
      },
      {
        brand: "Lenskart",
        type: "collab",
        platform: "instagram",
        title: "Not hype. Not bait.",
        url: "https://www.instagram.com/p/DIjSOXeTWSa/",
        date: "2025-04-17",
        likes: 33793, comments: 1072,
        note: "Second Lenskart collaboration — a repeat relationship, not a one-off.",
      },
      {
        brand: "Mokobara",
        type: "episode",
        platform: "youtube",
        title: "Brands Are FOOLING You by Selling CHEAP Chinese Products🤯 || Nitin Joshi",
        url: "https://www.youtube.com/watch?v=teKpEseuYQs",
        date: "2025-02-01",
        views: 32562,
        note: "Long-form breakdown of premium D2C pricing and white-labelling.",
      },
      {
        brand: "The Man Company",
        type: "episode",
        platform: "youtube",
        title: "D2C BLUEPRINT: Content, Celebrities & Influencer Marketing | Ft. Hitesh Dhingra | Nitin Joshi",
        url: "https://www.youtube.com/watch?v=wD5Any4_EjU",
        date: "2026-05-20",
        views: 4647,
        note: "Full episode with Hitesh Dhingra, who scaled it to ₹400 Cr and exited to Emami.",
      },
      {
        brand: "GoKwik",
        type: "collab",
        platform: "instagram",
        title: "🚨 Save Yourself from COD Losses! 🚫 Don’t let cash on delivery eat into your profits. With @gokwik.co , you can turn thos",
        url: "https://www.instagram.com/p/DBI9aEbvOnU/",
        date: "2024-10-15",
        likes: 10021, comments: 452,
        note: "Paid collaboration with the D2C checkout stack — speaks to founders directly.",
      },
      {
        brand: "Hyphen",
        type: "case-study",
        platform: "instagram",
        title: "Tag your DILLI wala friend….",
        url: "https://www.instagram.com/p/DM3A_k0TnkM/",
        date: "2025-08-02",
        likes: 87636, comments: 1182,
        note: "Celebrity-led D2C case study; one of the account's highest-reach business reels.",
      },
    ],
  },
  {
    id: "food-beverage",
    name: "Food & Beverage",
    picks: [
      {
        brand: "Lahori Zeera",
        type: "episode",
        platform: "youtube",
        title: "Here is how he made Lahori Zeera a ₹2,800 crore company! | Ft. Nikhil Doda | Nitin Joshi",
        url: "https://www.youtube.com/watch?v=_bMJT5YLko8",
        date: "2026-06-17",
        views: 9692,
        note: "Full episode with the co-founder of India's biggest ethnic beverage brand — 1 crore bottles a day.",
      },
      {
        brand: "Chai Sutta Bar",
        type: "episode",
        platform: "youtube",
        title: "How Chai Sutta Bar Actually Started? | Ft. Anubhav Dubey | Nitin Joshi",
        url: "https://www.youtube.com/watch?v=nOs1iPaFHAE",
        date: "2026-04-15",
        views: 23887,
        note: "Full episode with Anubhav Dubey on building a global chai franchise from ₹3 lakh.",
      },
      {
        brand: "Nilon's",
        type: "episode",
        platform: "youtube",
        title: "FMCG Expert: How to Spot Business Opportunities in the Unorganised Market",
        url: "https://www.youtube.com/watch?v=c5sb3_HQYaY",
        date: "2025-11-11",
        views: 28641,
        note: "Full episode with Dipak Sanghavi, who took the family pickle business from ₹8 Cr to ₹500+ Cr.",
      },
      {
        brand: "Jumboking",
        type: "episode",
        platform: "youtube",
        title: "How JumboKing is planning to BEAT McDonald’s in India? | Ft. Dheeraj gupta | Nitin Joshi #food",
        url: "https://www.youtube.com/watch?v=VurXs2vwUBg",
        date: "2026-03-11",
        views: 4198,
        note: "Full episode on scaling vada pav into a QSR chain against McDonald's and Burger King.",
      },
      {
        brand: "Jumboking",
        type: "clip",
        platform: "instagram",
        title: "In this episode, we talk to the founder of Jumboking, the brand that turned India’s vada pav into a scalable vegetarian",
        url: "https://www.instagram.com/p/DVQ0nclEpZr/",
        date: "2026-02-27",
        likes: 94, comments: 2,
        note: "The short-form cut from that episode — the long-form and the clip, which is the package.",
      },
      {
        brand: "Zomato",
        type: "case-study",
        platform: "instagram",
        title: "Numbers don’t lie and Zomato’s Q3 report is screaming SUCCESS!",
        url: "https://www.instagram.com/p/C3VP5Cfvy24/",
        date: "2024-02-14",
        likes: 544085, comments: 1229,
        note: "The account's highest-engagement food reel — a unit-economics breakdown of Zomato.",
      },
    ],
  },
  {
    id: "electronics",
    name: "Electronics",
    picks: [
      {
        brand: "Boult / Go Boult",
        type: "collab",
        platform: "instagram",
        title: "Two products can look the same, but one still charges double the price. 👀",
        url: "https://www.instagram.com/p/DNf9Ut4zIOn/",
        date: "2025-08-18",
        likes: 56846, comments: 526,
        note: "Brand collaboration covering the Go Boult rebrand and price-perception strategy.",
      },
      {
        brand: "Livguard",
        type: "collab",
        platform: "instagram",
        title: "We’ve all had those annoying power cut moments — right before a Zoom call, mid-study session, or just as you’re dozing o",
        url: "https://www.instagram.com/p/DLaFYd9Twbn/",
        date: "2025-06-27",
        likes: 19669, comments: 231,
        note: "Paid collaboration on a lithium inverter — consumer hardware, shot as a real use case.",
      },
      {
        brand: "ASUS",
        type: "collab",
        platform: "instagram",
        title: "Working from home can be a real productivity killer, right? 😅 I used to struggle too—working from my bed, endless distra",
        url: "https://www.instagram.com/p/C_weCF6sAuo/",
        date: "2024-09-11",
        likes: 7722, comments: 159,
        note: "Paid collaboration on a work-from-home laptop setup.",
      },
      {
        brand: "Realme",
        type: "episode",
        platform: "youtube",
        title: "Realme Ex-CEO Exposes the Smartphone Industry | Ft. Madhav Sheth | Nitin Joshi #startup",
        url: "https://www.youtube.com/watch?v=u7kDZ0sod0Q",
        date: "2025-12-21",
        views: 5972,
        note: "Full episode with Madhav Sheth on building a challenger smartphone brand in India.",
      },
      {
        brand: "Cashify",
        type: "episode",
        platform: "youtube",
        title: "Stop! Watch This Before Buying Any Refurbished Phone | Ft. Nakul Kumar | Nitin Joshi",
        url: "https://www.youtube.com/watch?v=2-_JPmra1Aw",
        date: "2026-04-29",
        views: 6894,
        note: "Full episode with Cashify's co-founder on smartphone recommerce and recycling.",
      },
      {
        brand: "Realme / OPPO",
        type: "clip",
        platform: "instagram",
        title: "The Untold Story of the Mind That Built Realme and OPPO",
        url: "https://www.instagram.com/p/DSmoSbGjg4q/",
        date: "2025-12-23",
        likes: 50, comments: 1,
        note: "The clip cut from the Madhav Sheth episode — long-form plus short-form, from one recording.",
      },
    ],
  },
  {
    id: "jewellery",
    name: "Jewellery",
    picks: [
      {
        brand: "Rubans Accessories",
        type: "episode",
        platform: "youtube",
        title: "How She Built a ₹100 Crore Business & Got Shark Tank Funding? | Ft. Chinu Kala | Nitin Joshi",
        url: "https://www.youtube.com/watch?v=7yYkpVW49Lo",
        date: "2026-07-01",
        views: 11457,
        note: "Full episode with the founder of one of India's largest fashion jewellery brands, 5M+ customers.",
      },
      {
        brand: "Palmonas",
        type: "collab",
        platform: "instagram",
        title: "Sone se zyada fayda sone ke business mai hai, kar sakte ho toh kar lo.",
        url: "https://www.instagram.com/p/DXUJTBKEyCZ/",
        date: "2026-04-19",
        likes: 7969, comments: 40,
        note: "Brand collaboration with a demi-fine jewellery D2C label.",
      },
      {
        brand: "The jewellery boom",
        type: "case-study",
        platform: "instagram",
        title: "Why is everyone getting into jewellery business?",
        url: "https://www.instagram.com/p/DbixWkrT5fS/",
        date: "2026-08-02",
        likes: 6230, comments: 32,
        note: "Reel on why jewellery is the most-entered category right now — a natural opener for a jewellery pitch.",
      },
      {
        brand: "Lab-grown diamonds",
        type: "case-study",
        platform: "instagram",
        title: "Natural vs Lab grown, the real talk you didn’t know you needed! Status, price, and what’s really going on in the diamond",
        url: "https://www.instagram.com/p/DOBaj1Xkzu6/",
        date: "2025-08-31",
        likes: 10513, comments: 514,
        note: "Lab-grown vs natural diamonds explained — the live debate in the category.",
      },
      {
        brand: "CaratLane",
        type: "case-study",
        platform: "instagram",
        title: "Story of caratlane.",
        url: "https://www.instagram.com/p/CwcmFYsxbLH/",
        date: "2023-08-27",
        likes: 485, comments: 23,
        note: "Case study of the Titan-backed jewellery brand.",
      },
      {
        brand: "Rubans Accessories",
        type: "clip",
        platform: "instagram",
        title: "Most people start a jewellery brand the wrong way.",
        url: "https://www.instagram.com/p/DaXfQH8SVm6/",
        date: "2026-07-04",
        likes: 76, comments: 1,
        note: "Short-form cut from the Rubans episode, made for reach.",
      },
    ],
  },
  {
    id: "skin-care-health",
    name: "Skin Care & Health",
    picks: [
      {
        brand: "Sunscreen testing",
        type: "case-study",
        platform: "instagram",
        title: "THE WAIT IS OVER!!",
        url: "https://www.instagram.com/p/DSKpW_7k9K3/",
        date: "2025-12-12",
        likes: 247673, comments: 1801,
        note: "The single highest-engagement post in the whole archive — a sunscreen efficacy test.",
      },
      {
        brand: "Lakmē",
        type: "collab",
        platform: "instagram",
        title: "Still tanning with SPF on?",
        url: "https://www.instagram.com/p/DIrKrzpzQ1N/",
        date: "2025-04-20",
        likes: 5454, comments: 275,
        note: "Paid collaboration on SPF testing — a category-native brand partnership.",
      },
      {
        brand: "Naturali",
        type: "collab",
        platform: "instagram",
        title: "Bhai mere dost ki baalo ki dikkatein toh solve hui hi, saath me uska confidence bhi bhad gya hai. Toh bhai aap bhi try k",
        url: "https://www.instagram.com/p/DSSU8sxE7hZ/",
        date: "2025-12-15",
        likes: 16077, comments: 385,
        note: "Paid collaboration on an anti-hairfall shampoo.",
      },
      {
        brand: "Fixderma",
        type: "episode",
        platform: "youtube",
        title: "New Judge EXPOSED Shark Tank India Secrets! | Ft. Shaily Mehrotra | Nitin Joshi #business",
        url: "https://www.youtube.com/watch?v=jG1W2xdHfMY",
        date: "2026-02-20",
        views: 14833,
        note: "Full episode with Shaily Mehrotra, who built a ₹1,500+ Cr global skincare brand.",
      },
      {
        brand: "Just Herbs",
        type: "episode",
        platform: "youtube",
        title: "LIFE after Rs100 Crore Exit...... | Ft. Arush Chopra | Nitin Joshi #startup",
        url: "https://www.youtube.com/watch?v=gAurOAH8Gq0",
        date: "2025-12-10",
        views: 8927,
        note: "Full episode with the founder of the clean-beauty brand acquired by Marico.",
      },
      {
        brand: "Ubik Solutions",
        type: "episode",
        platform: "youtube",
        title: "How a Rajkot Startup became an ₹850 Crore Brand? | Ft. Ilesh Khakhkhar | Nitin Joshi",
        url: "https://www.youtube.com/watch?v=FkUxV53g0nU",
        date: "2026-08-07",
        views: 3121,
        note: "Full episode with the founder of a ₹300 Cr dermaceutical business.",
      },
    ],
  },
  {
    id: "finance-insurance",
    name: "Finance & Insurance",
    picks: [
      {
        brand: "ICICI Prudential Life",
        type: "collab",
        platform: "instagram",
        title: "Everyone says “I’ll do it later” when it comes to term insurance, but life doesn’t always wait.",
        url: "https://www.instagram.com/p/DM-Zw4xzSwf/",
        date: "2025-08-05",
        likes: 102499, comments: 2273,
        note: "Paid collaboration on term insurance — the campaign already used in the sample deck.",
      },
      {
        brand: "ICICI Prudential Life",
        type: "collab",
        platform: "instagram",
        title: "Invest in child’s future with Smartkid with ICICI Pru Smartlife Plan! 💰 Secure their education with this ULIP investmen",
        url: "https://www.instagram.com/p/C8ChfrmSoUZ/",
        date: "2024-06-10",
        likes: 12792, comments: 230,
        note: "Second ICICI Pru collaboration — a child-plan ULIP.",
      },
      {
        brand: "Paytm",
        type: "collab",
        platform: "instagram",
        title: "UPI aur credit market se insight nikaal ke bna diya Paytm Postpaid, ₹60,000 credit limit - seedha UPI se.",
        url: "https://www.instagram.com/p/DYHscrtzSli/",
        date: "2026-05-09",
        likes: 6383, comments: 52,
        note: "Paid collaboration on Paytm Postpaid credit.",
      },
      {
        brand: "Cyber safety",
        type: "collab",
        platform: "instagram",
        title: "#Ad",
        url: "https://www.instagram.com/p/DJ1jD2DzRA9/",
        date: "2025-05-19",
        likes: 80612, comments: 563,
        note: "Paid collaboration on digital payment fraud — ₹20,000 Cr lost annually.",
      },
      {
        brand: "Info Edge",
        type: "episode",
        platform: "youtube",
        title: "What he saw before investing in Zomato & Policybazaar? | Ft. Sanjeev Bikhchandani | Nitin Joshi",
        url: "https://www.youtube.com/watch?v=s8IIRqdYNa8",
        date: "2026-07-15",
        views: 3489,
        note: "Full episode with Sanjeev Bikhchandani, Naukri founder and early Zomato backer.",
      },
      {
        brand: "Bajaj Allianz General Insurance",
        type: "episode",
        platform: "youtube",
        title: "CEO Thinking Explained!! | Ft. Tapan Singhel | Nitin Joshi #mindset",
        url: "https://www.youtube.com/watch?v=PO8PQt9nFDI",
        date: "2026-03-18",
        views: 2562,
        note: "Full episode with its CEO, the \"Insurance Man of India\".",
      },
    ],
  },
  {
    id: "alcohol-spirits",
    name: "Alcohol & Spirits",
    picks: [
      {
        brand: "Woodsmen Mountain Whiskey",
        type: "episode",
        platform: "youtube",
        title: "How to start an ALCOHOL Brand in India? | Ft. Shivam Ginglani | Nitin Joshi",
        url: "https://www.youtube.com/watch?v=oS_iKF4B5eI",
        date: "2026-05-06",
        views: 8660,
        note: "Full episode on building a new-age Indian whisky brand from scratch.",
      },
      {
        brand: "Woodsmen Mountain Whiskey",
        type: "clip",
        platform: "instagram",
        title: "A New Challenger Has Entered India’s Whisky Market | Nitin Joshi",
        url: "https://www.instagram.com/p/DYMmMeYy5YS/",
        date: "2026-05-11",
        likes: 14843, comments: 65,
        note: "The highest-reach clip cut from that episode.",
      },
      {
        brand: "Whisky, vodka & gin",
        type: "clip",
        platform: "instagram",
        title: "What really separates whisky, vodka and gin?",
        url: "https://www.instagram.com/p/Dca9aepPDrt/",
        date: "2026-08-24",
        likes: 1437, comments: 11,
        note: "Recent explainer clip from the alcohol series.",
      },
      {
        brand: "Celebrity spirits brands",
        type: "clip",
        platform: "instagram",
        title: "Why All Celebrities Are Entering Into Alcohol Business? | Nitin Joshi",
        url: "https://www.instagram.com/p/DYPMB5eyfn9/",
        date: "2026-05-12",
        likes: 191, comments: 0,
        note: "On celebrity-founded spirits brands — directly relevant to a new label.",
      },
      {
        brand: "Imported vs Indian spirits",
        type: "clip",
        platform: "instagram",
        title: "Are Foreigners Still Ruling India’s Liquor Industry? | Nitin Joshi",
        url: "https://www.instagram.com/p/DYhMvJTS49F/",
        date: "2026-05-19",
        likes: 60, comments: 0,
        note: "On import brands versus Indian-made spirits.",
      },
    ],
  },
  {
    id: "technology-ai-saas",
    name: "Technology, AI & SaaS",
    picks: [
      {
        brand: "Zoho",
        type: "collab",
        platform: "instagram",
        title: "Ye apke business ke liye game changer hai bhai, try zaroor karna. Proudly made in India.",
        url: "https://www.instagram.com/p/DQhRPt8E22P/",
        date: "2025-11-01",
        likes: 68525, comments: 253,
        note: "Paid collaboration — the made-in-India software pitch.",
      },
      {
        brand: "Zoho Workplace",
        type: "collab",
        platform: "instagram",
        title: "55% of Indian startups face challenges despite a solid business model.",
        url: "https://www.instagram.com/p/DIeOeAQzfB5/",
        date: "2025-04-15",
        likes: 8145, comments: 59,
        note: "Second Zoho collaboration, aimed at founders.",
      },
      {
        brand: "Odoo",
        type: "collab",
        platform: "instagram",
        title: "Studies show that 60% of customers say “no” at least 4 times before saying “yes,” but 33% of sales agents give up after",
        url: "https://www.instagram.com/p/DDcIRiPzhj8/",
        date: "2024-12-11",
        likes: 16262, comments: 818,
        note: "Paid collaboration on CRM and sales follow-up.",
      },
      {
        brand: "Emergent Labs",
        type: "collab",
        platform: "instagram",
        title: "Ya toh AI Mai kuch bana lo varna @emergentlabs se kuch bana lo, business ke rocket lag jayenge.",
        url: "https://www.instagram.com/p/DT26eAaE6Ow/",
        date: "2026-01-23",
        likes: 29217, comments: 220,
        note: "Paid collaboration with an AI app-building platform — one of three in the series.",
      },
      {
        brand: "Excitel Broadband",
        type: "episode",
        platform: "youtube",
        title: "From Kashmir to building an INTERNET Empire | Ft. Vivek Raina | Nitin Joshi #internet",
        url: "https://www.youtube.com/watch?v=DrnjuK3FdNU",
        date: "2026-02-08",
        views: 3932,
        note: "Full episode with the founder of a fast-growing wired broadband provider.",
      },
      {
        brand: "Coratia Technologies",
        type: "episode",
        platform: "youtube",
        title: "What AI And Robots Will Actually Look Like In India By 2030 | Ft. Debendra Pradhan | Nitin Joshi",
        url: "https://www.youtube.com/watch?v=FZ44zJTUZrQ",
        date: "2026-04-22",
        views: 3366,
        note: "Full episode on a deep-tech robotics startup.",
      },
    ],
  },
  {
    id: "education-edtech",
    name: "Education & EdTech",
    picks: [
      {
        brand: "IIM Ranchi",
        type: "collab",
        platform: "instagram",
        title: "Did you know 80% of India’s unicorn founders are from IITs, IIMs, or top global B-schools? 💡",
        url: "https://www.instagram.com/p/DE2d63JzYQF/",
        date: "2025-01-15",
        likes: 30603, comments: 8442,
        note: "Paid collaboration on the CXO programme — the account's best-performing education post.",
      },
      {
        brand: "IIM Ranchi",
        type: "collab",
        platform: "instagram",
        title: "Your Dream Career Starts Here—No CAT Required!",
        url: "https://www.instagram.com/p/DDPYcj6Ti-r/",
        date: "2024-12-06",
        likes: 18285, comments: 8312,
        note: "Second IIM Ranchi collaboration.",
      },
      {
        brand: "PhysicsWallah",
        type: "case-study",
        platform: "instagram",
        title: "PhysicsWallah scaled the company when other ed-tech players were struggling. From YouTube to IPO, it’s a case study in t",
        url: "https://www.instagram.com/p/DQuE7JRkwwg/",
        date: "2025-11-06",
        likes: 90201, comments: 630,
        note: "High-reach case study on the edtech that scaled to IPO while peers struggled.",
      },
      {
        brand: "upGrad",
        type: "collab",
        platform: "instagram",
        title: "Skills are great, but a degree opens doors! Want to Level up? Pursue this 1-year MBA from OP Jindal Global University wh",
        url: "https://www.instagram.com/p/DAoLC3MPzI0/",
        date: "2024-10-02",
        likes: 9439, comments: 122,
        note: "Paid collaboration on an online MBA.",
      },
      {
        brand: "LPU",
        type: "collab",
        platform: "instagram",
        title: "Imagine getting grades for growing your Instagram, launching a startup, or acing freelancing projects. Sounds unreal? No",
        url: "https://www.instagram.com/p/DHv4RN4z7Xg/",
        date: "2025-03-28",
        likes: 10772, comments: 95,
        note: "Paid collaboration with Lovely Professional University.",
      },
      {
        brand: "College Vidya",
        type: "collab",
        platform: "instagram",
        title: "📢 Compare 100+ Top-Tier Online Universities on 30+ key factors like fees, faculty, placements, and more—only @collegevid",
        url: "https://www.instagram.com/p/DHlAVX8TyYK/",
        date: "2025-03-24",
        likes: 11194, comments: 442,
        note: "Paid collaboration with an online-degree comparison platform.",
      },
    ],
  },
  {
    id: "real-estate-construction",
    name: "Real Estate & Construction",
    picks: [
      {
        brand: "Signature Global",
        type: "collab",
        platform: "instagram",
        title: "Jaise Delhi ke liye Gurgaon aaya, ab Gurgaon ke liye Manesar. Toh bhai time se pehle sahi real estate mai invest karo. C",
        url: "https://www.instagram.com/p/DSVAx9cE7ai/",
        date: "2025-12-16",
        likes: 20824, comments: 274,
        note: "Paid collaboration with a listed NCR developer.",
      },
      {
        brand: "Commercial property",
        type: "case-study",
        platform: "instagram",
        title: "Real estate: Commercial property is a scam.",
        url: "https://www.instagram.com/p/DDR57bnz7WC/",
        date: "2024-12-07",
        likes: 165755, comments: 1134,
        note: "The account's highest-engagement real-estate reel.",
      },
      {
        brand: "House of Abhinandan Lodha",
        type: "case-study",
        platform: "instagram",
        title: "Zepto se Zameen? 🤯 The House of Abhinandan Lodha ne Zepto ke saath partnership karke marketing ke saare rules todd diye",
        url: "https://www.instagram.com/p/DNa_7BzzPf3/",
        date: "2025-08-16",
        likes: 32913, comments: 331,
        note: "Case study of their Zepto partnership — land sold through quick commerce.",
      },
      {
        brand: "DLF",
        type: "case-study",
        platform: "instagram",
        title: "Discover how DLF is redefining luxury living, just like Louis Vuitton redefines fashion. Watch the reel to see how DLF s",
        url: "https://www.instagram.com/p/C7HLSAxyVEP/",
        date: "2024-05-18",
        likes: 67142, comments: 303,
        note: "Case study positioning DLF against luxury fashion houses.",
      },
      {
        brand: "Real-estate pricing",
        type: "case-study",
        platform: "instagram",
        title: "How pricing of Real Estate works? 💰",
        url: "https://www.instagram.com/p/DDhimn6TAPV/",
        date: "2024-12-13",
        likes: 9309, comments: 89,
        note: "Explainer on how developers actually price inventory.",
      },
    ],
  },
  {
    id: "automotive-ev",
    name: "Automotive & EV",
    picks: [
      {
        brand: "Livanto Green",
        type: "episode",
        platform: "youtube",
        title: "How to Start an EV Charging Business in 2026? | Ft. Ashwani Dixit | Nitin Joshi #electricvehicle",
        url: "https://www.youtube.com/watch?v=APzeZtT9mnU",
        date: "2026-03-25",
        views: 16545,
        note: "Full episode on building EV charging infrastructure.",
      },
      {
        brand: "Ethanol industry",
        type: "episode",
        platform: "youtube",
        title: "Nitin Gadkari, Ethanol Profits & Engine Damage: The E20 Petrol Controversy EXPLAINED! | Nitin Joshi",
        url: "https://www.youtube.com/watch?v=ntMegJncLjM",
        date: "2026-07-22",
        views: 12055,
        note: "Full episode on the E20 petrol controversy with an ethanol manufacturer.",
      },
      {
        brand: "Ola Electric",
        type: "case-study",
        platform: "instagram",
        title: "Ola Electric doing fake PR just to increase stock prices!!",
        url: "https://www.instagram.com/p/DOd09DvE2Em/",
        date: "2025-09-11",
        likes: 19467, comments: 319,
        note: "Case-study reel on Ola Electric's stock-price PR.",
      },
      {
        brand: "Mercedes-Benz",
        type: "case-study",
        platform: "instagram",
        title: "❌❌MERCEDES AT 10% PAYMENT…🔻🔻🔻",
        url: "https://www.instagram.com/p/DHqXZ9-zbEd/",
        date: "2025-03-26",
        likes: 51192, comments: 646,
        note: "High-reach reel on Mercedes' financing offer.",
      },
      {
        brand: "Livanto Green",
        type: "clip",
        platform: "instagram",
        title: "Airports are becoming the next EV hotspot.",
        url: "https://www.instagram.com/p/DWoLjivvuPV/",
        date: "2026-04-02",
        likes: 84, comments: 2,
        note: "Clip from the EV episode on their Adani Airports MOU — a named, checkable deal.",
      },
      {
        brand: "E20 petrol",
        type: "clip",
        platform: "instagram",
        title: "Is E20 really the reason behind this car problem?",
        url: "https://www.instagram.com/p/DbDmouIS8yE/",
        date: "2026-07-21",
        likes: 132, comments: 15,
        note: "Clip from the ethanol episode on the engine-damage claim.",
      },
    ],
  },
  {
    id: "fashion-apparel",
    name: "Fashion & Apparel",
    picks: [
      {
        brand: "Shoe Factory",
        type: "episode",
        platform: "youtube",
        title: "From ₹0 To ₹250Cr: A Tier-3 City Shoe Empire | Ft. Rajesh Motiyani | Nitin Joshi #business",
        url: "https://www.youtube.com/watch?v=9VMeQq-V-gU",
        date: "2026-01-25",
        views: 11142,
        note: "Full episode on a ₹250 Cr footwear brand built from Ratlam without funding.",
      },
      {
        brand: "Zara",
        type: "case-study",
        platform: "instagram",
        title: "Make your business like Zara.",
        url: "https://www.instagram.com/p/C501yZiyyna/",
        date: "2024-04-16",
        likes: 78398, comments: 399,
        note: "Case study on Zara's fast-fashion supply chain.",
      },
      {
        brand: "Nike",
        type: "case-study",
        platform: "instagram",
        title: "Nike se kickout.",
        url: "https://www.instagram.com/p/DF2xfStzKew/",
        date: "2025-02-09",
        likes: 12638, comments: 37,
        note: "Case-study reel on Nike's athlete and endorsement strategy.",
      },
      {
        brand: "Nike / Adidas",
        type: "case-study",
        platform: "instagram",
        title: "What is Ambush Marketing?",
        url: "https://www.instagram.com/p/C1cAFkYSSOP/",
        date: "2023-12-29",
        likes: 4066, comments: 15,
        note: "Explainer built on the Nike–Adidas rivalry.",
      },
      {
        brand: "Shoe Factory",
        type: "clip",
        platform: "instagram",
        title: "If you’re building a big business from a Tier-3 city, drop your view in the comments.",
        url: "https://www.instagram.com/p/DT7DTNfD3OB/",
        date: "2026-01-25",
        likes: 17838, comments: 77,
        note: "Clip from the Shoe Factory episode — the highest-reach post on the podcast account.",
      },
      {
        brand: "Shoe Factory",
        type: "clip",
        platform: "instagram",
        title: "Why would someone name a ₹250 Cr brand something so simple? This is the reason.",
        url: "https://www.instagram.com/p/DT9lSWykmV4/",
        date: "2026-01-26",
        likes: 399, comments: 5,
        note: "Second clip from that episode, on how the brand got its name.",
      },
    ],
  },
  {
    id: "recycling-sustainability",
    name: "Recycling & Sustainability",
    picks: [
      {
        brand: "ScrapUncle",
        type: "episode",
        platform: "youtube",
        title: "The ULTIMATE Guide to Turning Scrap into a ₹100 Crore Business | Ft. Mukul Chhabra | Nitin Joshi",
        url: "https://www.youtube.com/watch?v=OmfQ3ABvJrk",
        date: "2026-04-01",
        views: 30739,
        note: "Full episode on India's most organised tech-driven scrap platform.",
      },
      {
        brand: "Horizon Reclaim",
        type: "episode",
        platform: "youtube",
        title: "How this Man made Crores from Old Tyres? | Ft. Mohit Bajaj | Nitin Joshi",
        url: "https://www.youtube.com/watch?v=xCqD-JT7jD4",
        date: "2026-06-10",
        views: 22550,
        note: "Full episode on a ₹300 Cr tyre-recycling business heading to IPO.",
      },
      {
        brand: "Cashify",
        type: "episode",
        platform: "youtube",
        title: "Stop! Watch This Before Buying Any Refurbished Phone | Ft. Nakul Kumar | Nitin Joshi",
        url: "https://www.youtube.com/watch?v=2-_JPmra1Aw",
        date: "2026-04-29",
        views: 6894,
        note: "Recommerce — also listed under Electronics.",
      },
      {
        brand: "ScrapUncle",
        type: "clip",
        platform: "instagram",
        title: "From picking scrap himself to building ScrapUncle, Mukul Chhabra is organizing India’s unstructured scrap industry into",
        url: "https://www.instagram.com/p/DWl8hbpEjBn/",
        date: "2026-04-01",
        likes: 690, comments: 27,
        note: "Clip from the ScrapUncle episode, cut for reach.",
      },
      {
        brand: "Horizon Reclaim",
        type: "clip",
        platform: "instagram",
        title: "Ever Wondered what HAPPENS to old Tyres?",
        url: "https://www.instagram.com/p/DZmZM_EvwKa/",
        date: "2026-06-15",
        likes: 99, comments: 2,
        note: "Clip from the tyre-recycling episode.",
      },
    ],
  },
];

/** One category by id, or null. */
export function categoryById(id) {
  return CONTENT_CATEGORIES.find((c) => c.id === id) || null;
}

/**
 * Best-guess category for a scraped brand, matched on its own words —
 * description, about copy and page title. Returns null rather than guessing
 * when nothing matches, so the caller can fall back to the generic picks.
 */
const CATEGORY_HINTS = {
  "direct-to-consumer": ["d2c", "direct to consumer", "our own website", "shopify"],
  "food-beverage": ["food", "beverage", "snack", "coffee", "tea", "restaurant", "cafe", "bakery", "dairy", "fmcg", "drink", "juice", "chocolate", "spice", "masala"],
  "electronics": ["electronic", "appliance", "smartphone", "earbud", "headphone", "speaker", "laptop", "gadget", "inverter", "battery", "smartwatch", "television"],
  "jewellery": ["jewellery", "jewelry", "diamond", "gold", "silver", "ornament", "bridal"],
  "skin-care-health": ["skincare", "skin care", "cosmetic", "beauty", "serum", "sunscreen", "haircare", "hair care", "grooming", "wellness", "supplement", "nutrition", "ayurved", "pharma", "clinic", "diagnostic"],
  "finance-insurance": ["insurance", "bank", "lending", "loan", "mutual fund", "invest", "fintech", "payments", "credit"],
  "alcohol-spirits": ["whisky", "whiskey", "vodka", "gin", "rum", "beer", "brewery", "distillery", "liquor", "spirits", "wine"],
  "technology-ai-saas": ["saas", "software", "platform", "api", "artificial intelligence", " ai ", "cloud", "broadband", "internet service"],
  "education-edtech": ["edtech", "university", "college", "coaching", "course", "learning", "academy", "institute"],
  "real-estate-construction": ["real estate", "property", "developer", "housing", "construction", "cement", "interiors", "paint"],
  "automotive-ev": ["automotive", "electric vehicle", " ev ", "scooter", "motorcycle", "automobile", "car ", "charging"],
  "fashion-apparel": ["apparel", "clothing", "fashion", "footwear", "shoes", "sneaker", "ethnic wear", "denim", "eyewear"],
  "recycling-sustainability": ["recycl", "sustainab", "waste", "scrap", "circular economy", "refurbish"],
};

export function categoryForBrand(brand) {
  const hay = [
    brand?.name,
    brand?.description,
    brand?.about?.description,
  ]
    .filter(Boolean)
    .join(' ')
    .toLowerCase();
  if (!hay.trim()) return null;

  let best = null;
  let bestHits = 0;
  for (const [id, terms] of Object.entries(CATEGORY_HINTS)) {
    const hits = terms.filter((t) => hay.includes(t)).length;
    if (hits > bestHits) {
      bestHits = hits;
      best = id;
    }
  }
  return best ? categoryById(best) : null;
}
